/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StringlineIndexRouteImport } from './routes/stringline.index'
import { Route as StringlineConfigurationTodayRouteImport } from './routes/stringline.$configuration.today'
import { Route as StringlineConfigurationServiceDateRouteImport } from './routes/stringline.$configuration.$serviceDate'

const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StringlineIndexRoute = StringlineIndexRouteImport.update({
  id: '/stringline/',
  path: '/stringline/',
  getParentRoute: () => rootRouteImport,
} as any)
const StringlineConfigurationTodayRoute =
  StringlineConfigurationTodayRouteImport.update({
    id: '/stringline/$configuration/today',
    path: '/stringline/$configuration/today',
    getParentRoute: () => rootRouteImport,
  } as any)
const StringlineConfigurationServiceDateRoute =
  StringlineConfigurationServiceDateRouteImport.update({
    id: '/stringline/$configuration/$serviceDate',
    path: '/stringline/$configuration/$serviceDate',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/stringline': typeof StringlineIndexRoute
  '/stringline/$configuration/$serviceDate': typeof StringlineConfigurationServiceDateRoute
  '/stringline/$configuration/today': typeof StringlineConfigurationTodayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/stringline': typeof StringlineIndexRoute
  '/stringline/$configuration/$serviceDate': typeof StringlineConfigurationServiceDateRoute
  '/stringline/$configuration/today': typeof StringlineConfigurationTodayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/stringline/': typeof StringlineIndexRoute
  '/stringline/$configuration/$serviceDate': typeof StringlineConfigurationServiceDateRoute
  '/stringline/$configuration/today': typeof StringlineConfigurationTodayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faq'
    | '/stringline'
    | '/stringline/$configuration/$serviceDate'
    | '/stringline/$configuration/today'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faq'
    | '/stringline'
    | '/stringline/$configuration/$serviceDate'
    | '/stringline/$configuration/today'
  id:
    | '__root__'
    | '/'
    | '/faq'
    | '/stringline/'
    | '/stringline/$configuration/$serviceDate'
    | '/stringline/$configuration/today'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaqRoute: typeof FaqRoute
  StringlineIndexRoute: typeof StringlineIndexRoute
  StringlineConfigurationServiceDateRoute: typeof StringlineConfigurationServiceDateRoute
  StringlineConfigurationTodayRoute: typeof StringlineConfigurationTodayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stringline/': {
      id: '/stringline/'
      path: '/stringline'
      fullPath: '/stringline'
      preLoaderRoute: typeof StringlineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stringline/$configuration/today': {
      id: '/stringline/$configuration/today'
      path: '/stringline/$configuration/today'
      fullPath: '/stringline/$configuration/today'
      preLoaderRoute: typeof StringlineConfigurationTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stringline/$configuration/$serviceDate': {
      id: '/stringline/$configuration/$serviceDate'
      path: '/stringline/$configuration/$serviceDate'
      fullPath: '/stringline/$configuration/$serviceDate'
      preLoaderRoute: typeof StringlineConfigurationServiceDateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaqRoute: FaqRoute,
  StringlineIndexRoute: StringlineIndexRoute,
  StringlineConfigurationServiceDateRoute:
    StringlineConfigurationServiceDateRoute,
  StringlineConfigurationTodayRoute: StringlineConfigurationTodayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
